//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseResource
    {
        public int ResourceID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ChapterNO { get; set; }
        public string FileResource { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual CourseChapter CourseChapter { get; set; }
    }
}
