//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseChapter
    {
        public CourseChapter()
        {
            this.CourseResources = new HashSet<CourseResource>();
            this.Homework = new HashSet<Homework>();
            this.Tests = new HashSet<Test>();
        }
    
        public int ChapterNO { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string ChapterContent { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<CourseResource> CourseResources { get; set; }
        public virtual ICollection<Homework> Homework { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
    }
}
