//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseChapters = new HashSet<CourseChapter>();
            this.CourseResources = new HashSet<CourseResource>();
            this.Homework = new HashSet<Homework>();
            this.News = new HashSet<News>();
            this.Tests = new HashSet<Test>();
            this.Topics = new HashSet<Topic>();
            this.Assistants = new HashSet<Assistant>();
            this.Students = new HashSet<Student>();
        }
    
        public int CourseID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AreChapterSequential { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<CourseChapter> CourseChapters { get; set; }
        public virtual ICollection<CourseResource> CourseResources { get; set; }
        public virtual ICollection<Homework> Homework { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
        public virtual ICollection<Assistant> Assistants { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
