//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradedHomework
    {
        public int StudentID { get; set; }
        public int HomeworkID { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Homework Homework { get; set; }
        public virtual Student Student { get; set; }
    }
}
