//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Body { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
