//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.GradedHomeworks = new HashSet<GradedHomework>();
            this.StudentToTests = new HashSet<StudentToTest>();
            this.Courses = new HashSet<Course>();
        }
    
        public int StudentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> CardNO { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<GradedHomework> GradedHomeworks { get; set; }
        public virtual ICollection<StudentToTest> StudentToTests { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
