//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentToTest
    {
        public int StudentID { get; set; }
        public int TestID { get; set; }
        public Nullable<int> AttemptsRemaining { get; set; }
        public Nullable<int> LastGrade { get; set; }
        public Nullable<int> MaxGrade { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Test Test { get; set; }
    }
}
