//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.StudentToTests = new HashSet<StudentToTest>();
        }
    
        public int TestID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ChapterNO { get; set; }
        public string IsMandatory { get; set; }
        public Nullable<System.TimeSpan> AllocatedTime { get; set; }
        public Nullable<int> NoOfAttempts { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Structure { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual CourseChapter CourseChapter { get; set; }
        public virtual ICollection<StudentToTest> StudentToTests { get; set; }
    }
}
