//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int ThreadID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public string Title { get; set; }
        public string DescriptionT { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
