//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Learning.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Threads = new HashSet<Thread>();
        }
    
        public int TopicID { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
